// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mchtugsqopmnvbxwwjul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jaHR1Z3Nxb3BtbnZieHd3anVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDI1MzEsImV4cCI6MjA2ODYxODUzMX0.rJWXSMifPtSFjQ-Fg1UWEkiow_T-QL3yuDsyOzGtsqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});